#ifndef INCLUDES_H
#define INCLUDES_H
#include <QtSql>
#include <ctime>
#include <QThread>
#include <unistd.h>
#include <QThread>
#include <thread>
#include <QDateTime>
#include <QTime>
#include <QObject>
#include <QtConcurrent>
#include <QtConcurrentRun>
#include <QString>
#include <QDebug>
#include <QCanBus>
#include <libsocketcan.h>
#include <error.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <linux/can.h>
#include <net/if.h>
#include <unistd.h>
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QtWidgets/QApplication>
#include <QtQuick/QQuickView>
#include <QtCore/QDir>
#include <QtQml/QQmlEngine>
#include <QtQuick>
#include <QDateTime>
#include <QThread>
#include <thread>
#include <QtConcurrent>
#include <QMutex>
#include <QVector>
#include <QDesktopServices>
#include <QScreen>
#include <QTimer>
#include <X11/Xlib.h>
#include <QEvent>
#include <QTranslator>
#include <QDir>
#endif // INCLUDES_H
